Eliminate warnings in downstream projects
orchestrated-io/orcs-design-system pull request #165
Opened 2022-04-25 21:31 UTC by jensmithorcio

- Add shouldForwardProp config to select component styled divs to remove warning re invalid div attributes (width, height etc)
- Use styled-system props to ensure proptypes validation passes for valid styled-system properties

2022-04-25 22:23 UTC, KaranAtTeamForm commented on lib/components/Select/index.js
> +    SelectStyles
Lint errors.

2022-04-25 22:24 UTC, KaranAtTeamForm approved these changes
LGTM :)

2022-04-25 23:56 UTC, KaranAtTeamForm approved these changes
Build failing because of audit-ci vulnerabilities.

2022-04-25 23:56 UTC, KaranAtTeamForm requested changes
Build failing because of audit-ci vulnerabilities.

2022-04-26 02:57 UTC, KaranAtTeamForm approved these changes

2022-04-26 03:12 UTC, shomukai approved these changes

2022-04-26 03:39 UTC, deividasm approved these changes

2022-04-26 04:22 UTC, merged