Add Tag strikethrough accessibility label [5.5]
orchestrated-io/orcs-design-system pull request #205
Opened 2023-07-14 00:22 UTC by jsntv200

Add a hidden `Striked out:` when enabled.

Before:
```html
<div class="Tag__TagValueText-sc-1dh2aa8-2 hhoPgf">
  devops
</div>
```

After:
```html
<div class="Tag__TagValueText-sc-1dh2aa8-2 hhoPgf">
  <span class="sr-only">Striked out:</span>
  devops
</div>
```

2023-07-18 02:11 UTC, abottega requested changes
sr-only styles need to be added to: /orcs-design-system/lib/GlobalStyles.js

2023-07-18 05:16 UTC, jsntv200 commented
Actually I just copy / pasted that. But looking now its defined in font-awesome from the looks of it. Redefine in the global styles?

2023-08-01 06:27 UTC, abottega commented
> Actually I just copy / pasted that. But looking now its defined in font-awesome from the looks of it. Redefine in the global styles?

Ah yeah, it is too, didn't realise the css coming from font-awesome included the sr-only class styles.

All good, just need to change class to className, then this one is ready to go @jsntv200

2023-08-04 02:11 UTC, abottega approved these changes

2023-08-04 02:11 UTC, merged